chore: rename settings keys, remove keys
unik-name/discourse-unikname-connect-authentication-plugin pull request #5
Opened 2020-10-16 07:00 UTC by ftreguer

2020-10-16 09:18 UTC, dlecan requested changes

2020-10-16 09:18 UTC, dlecan commented on README.md
> +Before to [report en issue in github](https://github.com/unik-name/discourse-unikname-connect-authentication-plugin/issues) you're welcome to [open a discussion with the support on our Forum](https:/
Relative link?

2020-10-16 09:18 UTC, dlecan commented on config/settings.yml
> +  unikname_connect_Business_Account_ID:
lowercased

2020-10-16 09:18 UTC, dlecan commented on config/settings.yml
> +  unikname_connect_API_secret_key:
lowercased

2020-10-16 09:18 UTC, dlecan commented on lib/unikname_connect_authenticator.rb
> +        token_params[:scope] = ""
missing `openid` here?

2020-10-16 09:24 UTC, ftreguer commented on README.md
> +Before to [report en issue in github](https://github.com/unik-name/discourse-unikname-connect-authentication-plugin/issues) you're welcome to [open a discussion with the support on our Forum](https:/
?

2020-10-18 20:21 UTC, dlecan approved these changes

2020-10-18 20:21 UTC, merged